Plugin = require 'plugin'
{tr} = require 'i18n'

exports.questions = questions = -> [
    ["stolen alcohol from my parents", true],
    ["cheated in a competition", false],
    ["eaten cake", false],
    ["finished an entire jawbreaker", false],
    ["shaved my balls", false],
    ["smoked weed", false],
    ["killed an animal when not hunting", false],
    ["been in handcuffs", false],
    ["kissed someone on the first date", false],
    ["skipped school", false],
    ["had a close brush with death", false],
    ["fallen asleep in the cinema", false],
    ["done something I regret", false],
    ["been to church and to a gay bar on the same day", false],
    ["been skydiving", false],
    ["peed my pants in public  ", false],
    ["drank while underage", false],
    ["been in the hospital", false],
    ["grabbed electric fence", false],
    ["been in a car accident", false],
    ["read a whole Harry Potter book", false],
    ["felt like killing someone", false],
    ["peed on a bush", false],
    ["dated someone older than me", false],
    ["thrown up on a perfect stranger", false],
    ["been on tv", false],
    ["ran away", false],
    ["played this game", false],
    ["shot a gun", false],
    ["eaten alligator meat ", false],
    ["been in love with a family member", false],
    ["picked my nose", false],
    ["pressured a friend to break up", false],
    ["farted and blamed it on a pet", false],
    ["donated blood", false],
    ["been caught drinking and driving", false],
    ["gone fishing", false],
    ["sat in the backseat of a police cruiser", false],
    ["shaved my head", false],
    ["eaten a bug", false],
    ["sang in the shower", false],
    ["attempted suicide", false],
    ["pointed a gun at someone", false],
    ["told a teacher what I really thought of an assignment", false],
    ["kissed any one of my facebook friends", false],
    ["made fun of Justin Beiber", false],
    ["had surgery", false],
    ["sleepwalked", false],
    ["kissed someone", false],
    ["broken a bone", false],
    ["hit on someone while on a date with someone else", false],
    ["dumped someone ", false],
    ["jumped off a cliff", false],
    ["caused someone to need stitches", false],
    ["laughed until something I was drinking came out of my nose", false],
    ["injected or swallowed drugs", false],
    ["hit a home run", false],
    ["got caugh sneaking out", false],
    ["read the bible", false],
    ["eaten elk ", false],
    ["jumped in a pool with clothes on", false],
    ["bungy jumped", false],
    ["peed in the shower", false],
    ["written graffiti", false],
    ["traveled by myself", false],
    ["stolen", false],
    ["aced a test without studying", false],
    ["streaked", false],
    ["lost someone special", false],
    ["seen someone die", false],
    ["smuggled something into another country", false],
    ["totalled a car", false],
    ["cussed out somebody in Spanish", false],
    ["turned someone down", false],
    ["passed out when not drinking", false],
    ["had a friend turn on me", false],
    ["gotten bullyed", false],
    ["given a lap dance to a total stranger", false],
    ["gone in public without a bra", false],
    ["been pregnant", false],
    ["cheated on a test or exam", false],
    ["been in a band", false],
    ["held a snake", false],
    ["been spanked", false],
    ["experienced love at first sight", false],
    ["kissed in the rain", false],
    ["been cheated on", false],
    ["dated someone twice", false],
    ["hooked up with a teacher", false],
    ["taken a blow job shot", false],
    ["gotten a tattoo", false],
    ["ran a red light", false],
    ["taken by ambulance to hospital", false],
    ["sat on a rooftop", false],
    ["been depressed", false],
    ["ridden a surfboard", false],
    ["gotten so sick I swore off a particular type of alcohol", false],
    ["drank hard liquor", false],
    ["caught a snowflake on my tongue", false],
    ["owned an Iphone", false],
    ["changed clothes in a vehicle", false],
    ["forgotten my anniversary", false],
    ["gone a week without showering", false],
    ["knitted", false],
    ["snuck into a movie without paying", false],
    ["eaten snake", false],
    ["peed in a public pool", false],
    ["walked a moonlit beach", false],
    ["ridden in a helicopter", false],
    ["crawled through a window", false],
    ["gone to a club with a fake ID", false],
    ["had cops show up to my party", false],
    ["done something I could get a prison sentence for", false],
    ["stolen from a friend", false],
    ["cursed at a teacher to their face", false],
    ["had my parents ask me if I were a virgin", false],
    ["been to Disneyland", false],
    ["rode on a roller coaster with a loop", false],
    ["cried myself to sleep", false],
    ["had a temper tantrum in school", false],
    ["have you ever tripped in public", false],
    ["swam in the ocean", false],
    ["driven a stick shift", false],
    ["eaten a whole habenero pepper", false],
    ["gotten fooled on April Fools", false],
    ["fooled around in lessons", false],
    ["submited someone elses assignement as your own", false],
    ["shoplifted", false],
    ["sang karaoke", false],
    ["prank called anyone", false],
    ["drank and drove", false],
    ["been a bully", false],
    ["been called a tease", false],
    ["been frisked", false],
    ["been fired from a job", false],
    ["been arrested", false],
    ["found out someone was talking about me", false],
    ["played strip poker", false],
    ["wanted a friends boyfriend", false],
    ["gotten me braces locked together kissing someone", false],
    ["kissed a stranger", false],
    ["made out under the stars", false],
    ["fallen asleep in class and woken up in a puddle of drool", false],
    ["drank so much I did not remember my whole night", false],
    ["puked on amusement ride", false],
    ["given someone a fake phone number", false],
    ["peed in a bottle", false],
    ["been suspended from school", false],
    ["smoked a cigar", false],
    ["gone to jail", false],
    ["smoked up in the bathroom of high school", false],
    ["committed a felony", false],
    ["been pushed into a pool with my clothes on", false],
    ["shot spit balls in class", false],
    ["lied about my birthday just to get a free dessert", false],
    ["played Spin the Bottle", false],
    ["laughed so hard I peed", false],
    ["skinny dipped", false],
    ["wished for something bad to happen to someone I knew", false],
    ["rode a motorcycle", false],
    ["passed out with my head in the toilet", false],
    ["farted in an elevator and blamed in on someone else", false],
    ["lied to avoid a ticket", false],
    ["slept on the job", false],
    ["run from a police officer", false],
    ["talked my way out of a traffic ticket", false],
    ["had a shotgun wedding", false],
    ["lied about myself to get laid", false],
]

# determines duration of the round started at 'currentTime'
exports.getRoundDuration = (currentTime) ->
    return false if !currentTime

    duration = 3*3600
    while 23 <= (hrs = (new Date((currentTime+duration)*1000)).getHours()) or hrs <= 9
        duration += 3*3600

    duration

exports.indexToQuestion = (q) ->
    stringToQuestion questions[q][0]

exports.stringToQuestion = stringToQuestion = (s) ->
    "Never have I ever " + s
